version: '3.3'

services:
    app-db:
        image: mysql
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'apppassword'
        networks:
            - backend

    rest-services:
        image: jluck/village-services
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'
            DB_HOST: 'app-db'
            DB_PORT: '3306'
        links:
            - app-db
        networks:
            - frontend
            - backend
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 30s
        
networks:
    backend:
        driver: overlay
    frontend:
        driver: overlay


